project:
  type: website
  output-dir: docs

website:
  title: "Instructional Pedagogy"
  favicon: images/favicon.png
  site-path: "/Instructional-Pedagogy/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Pedagogy Lessons"
        menu: 
         - introductions.qmd
         - building-skill.qmd
         - memory-learning.qmd
         - learning-goals.qmd
         - motivation-demotivation.qmd
         - lesson-development.qmd
         - eia.qmd
         - feedback-how-to.qmd
         - live-coding.qmd
      - href: data-science-lessons.qmd
        text: Data Science Lessons
      - about.qmd
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: united
    css: styles.css
    toc: true
    page-layout: full
  pdf:
    toc: true
    color-links: true


