---
title: "Equity, inclusion, & accessibility"
---

## Lesson objectives

+ Identify instructional strategies that are consistent with universal design
+ Recognize systemic factors that can distract and demotivate students

## Overview

As we have seen, there are many teaching practices that can make your class 
more positive and welcoming. However, no class occurs in a vacuum: everyone's 
experiences begin and end and are influenced by the world beyond. In this 
section we will discuss some of the systemic barriers that can result in 
members of some groups being excluded even in an otherwise welcoming 
environment. The fact that some groups face barriers that others do not means 
we cannot take a one size fits all approach to creating a positive learning 
environment.

## Definitions

This section addresses topics related to equity, inclusion, and accessibility. 
These terms are increasingly common and may be familiar to you, but not 
everyone understands or interprets them in the same way. So, we will start with 
a few working definitions, adapted from the University of Pittsburgh DEI 
Glossary:

**Equity**: The proportional distribution of desirable outcomes across groups. 
Sometimes confused with equality, equity refers to outcomes while equality 
connotes equal treatment.

**Inclusion**: Actively engaging traditionally excluded individuals and/or 
groups in processes, activities and decisions in a way that shares power. 
Inclusion promotes broad engagement, shared participation, and advances 
authentic sense of belonging through safe, positive, and nurturing 
environments.

**Accessibility**: Refers to the intentional design or redesign of technology, 
policies, products, and services (to name a few) that increase one's ability to 
use, access, and obtain the respective item. Each person is afforded the 
opportunity to acquire the same information, engage in the same interactions, 
and enjoy the same services in an equally effective and equally integrated 
manner, with substantially equivalent ease of use.

### Equity versus Equality

We can monitor our own use of stereotypes, but the experiences that people have 
before and after our classes are beyond our control. Because these experiences 
are unequal, including historical and present-day differences in access to 
resources, mentorship, and other avenues towards career success, we should aim 
to make students' experiences _equitable_. This means that, rather than 
offering the same access and experience to all, we should craft our instruction
to actively counter-balance unequal opportunities that have led to 
disproportionate representation of historically marginalized groups in 
data-centric careers. In doing this, we focus on increasing accessibility and 
acknowledging and, when possible, countering systemic biases.

## Accessibility and universal design

Accommodation means changing things to serve an individual with a demonstrated 
need. However, accommodation puts the onus on the individual with the need to 
have to disclose their disability and ask for accommodations. Reluctance to do 
so is understandable: requests for accommodation are often met with negative 
emotions such as uncertainity, confusion, annoyance or anger by those receiving 
the requests.

By contrast, "universal design" means creating something to be maximally usable 
by all people without additional changes. A good example of universal design is 
curb cuts and sidewalk ramps. While they were originally created to make it 
easier for wheelchair users to move around, they proved to be equally helpful 
to people with strollers and grocery carts.

Universal design places responsibility for accessibility on the course designer 
rather than on the learner. It states that the most inclusive approach to 
education is to design instruction with diverse students in mind from the 
beginning. There is a wealth of information on universal design at the 
[UDL Guidelines](https://udlguidelines.cast.org/) site, which will be the focus
of a later exercise.

It’s easy to be overwhelmed by all the different ways we could make instruction 
more accessible. A couple things to remember:

+ It is ok not to do everything at once. Try to build in accessibility habits 
when preparing for workshops through reflective practice, adding something new 
each time.
+ Do the easy things first. There are plenty of ways to make workshops more 
accessible that are both quick to accomplish and minimal in demands on 
attention: font choices, text size, checking in advance that your room is 
accessible via an elevator or ramp, etc.

***

**Exercise**

What is one thing you could do in your classes to improve accessibility? What 
is one thing you would like to do, but you don't know how or are prevented from 
doing so by external factors? Add your answers to the collaborative document.

***

The [UDL Guidelines](https://udlguidelines.cast.org/) provides a framework for 
developing and delivering teaching materials that are inclusive and accessible 
from the start. We are going to leave it to you to take a deeper dive into the 
material, but for now we will just look at three of the ways to make the 
learning experience accessible.

***

**Exercise**

Pick one of the following UDL Guidelines checkpoints:

+ [Optimize relevance, value, and authenticity](https://udlguidelines.cast.org/engagement/recruiting-interest/relevance-value-authenticity)
+ [Highlight patterns, critical features, big ideas, and relationships](https://udlguidelines.cast.org/representation/comprehension/patterns-features)
+ [Guide appropriate goal-setting](https://udlguidelines.cast.org/action-expression/executive-functions/goal-setting/goal-setting)

On your own, read the description and bullet point action items for the 
checkpoint you chose. Pick (at least) one of the bullet points and describe how 
you could use it in designing or delivering material in your class.

***

## Systemic bias

As instructors, many aspects of our classroom environment are within our 
control or influence. However, the world is a complicated place, and there will 
always be extraneous factors that contribute to demotivation and add to 
cognitive load. These vary from person to person, but members of historically 
marginalized groups often carry a heavier load due to systemic forces that 
disproportionately impact them. What we can control, in this case, is our own 
awareness of the challenges these forces present to teaching and learning. As 
with other demotivation pitfalls, we can also think carefully about the 
language that we use and how we interact with our students to avoid reinforcing 
systemic bias.

### Stereotypes

We all use stereotypes, and for good reason. They serve a cognitive purpose. 
One study suggests we encounter more than 34 gigabytes of information every 
day. That is more information than we could ever process, so our brains use 
shortcuts. What an expert thing to do! Stereotypes are one of those shortcuts. 
As with other models, they are all wrong, but some are dangerous. What are 
stereotypes?

Stereotypes are an established feature of human social cognition, in which a 
set of characteristics is associated with members of a group. Sterotypes:

+ may be explicit (conscious and deliberate) or implicit (unconscious and 
  automatic)
+ guide what we notice about people
+ guide how we interpret people’s behaviors
+ can facilitate quick judgments in appropriate situations (e.g. stopping a 
  child from driving a car)
+ can lead to systematically negative attitudes and behaviors towards members 
of historically marginalized groups

Stereotypes are dangerous when they are explicit, but they are especially 
hazardous when they are implicit. This means that the people holding them may 
not be aware of them, even though their perceptions are guided by them.

When instructors have stereotypes about students, this may lead them to:

+ call attention to differences unnecessarily
+ give more or less attention to students from historically marginalized groups
+ respond to questions differently for students historically marginalized 
groups

When students experience stereotypes about themselves, they may:

+ develop a fixed mindset about aspects of their own capability
+ experience increased cognitive load when reminded about a stereotype, 
interfering with the learning process. This is known as _stereotype threat_.

What can we do about our own stereotypes? Most importantly, we can become aware 
of them. This isn't something that often happens overnight, but some steps you 
can take are:

+ Get to know people from many different groups!
+ Observe your own behavior, and build awareness of situations in which your 
perceptions and behaviors are influenced by stereotypes.
+ Avoid calling attention to common stereotypes, even in a way that seems 
positive.

## Reflection

***

**Exercise**

Considering what we covered about equity, inclusivity, and accessibility, what 
actions could you take to improve equity, inclusivity, or accessibility. If 
there is something you _want_ to change, but do not know how, add that to the 
collaborative document. If possible, discuss this as a group.

***

## Preparation for next week

***

**Homework**

Next week you will have multiple opportunities to practice 
teaching for short stretches and receive feedback on your teaching. Between now 
and the next session, please pick out something that you would like to teach to 
your fellow participants. This would ideally be some form of hands-on training 
for a beginner or intermediate audience. If you do not feel you have something 
you are comfortable teaching, we can provide some lessons from the Carpentries 
curriculum for you to work with.

***

## Feedback on the day

Your instructor will ask for you to provide feedback on this session.